### ISSUE TITLE
Breaking with new @hotwired/stimulus namespace

### ISSUE THREAD

**Issue by joshellington** [stimulus-components/stimulus-read-more#3]
If you're currently using the new namespace for `@hotwired/stimulus` this component (and others) do not build/compile. Link to deprecated npm package page: https://www.npmjs.com/package/stimulus

And announcement from DHH: https://world.hey.com/hotwired/stimulus-3-c438d432

**Comment by guillaumebriday** [comment]
https://github.com/stimulus-components/stimulus-read-more/releases/tag/v3.0.0
